const QUOTES = [
  { text: "Conhece-te a ti mesmo.", author: "Sócrates" },
  { text: "Somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito.", author: "Aristóteles" },
  { text: "A esperança é o sonho do homem acordado.", author: "Aristóteles" },
  { text: "Só existe um modo de evitar a crítica: não diga nada, não faça nada, não seja nada.", author: "Aristóteles" },
  { text: "A necessidade é a mãe da invenção.", author: "Platão" },
  { text: "Não importa quão lento você vá, desde que não pare.", author: "Confúcio" },
  { text: "A maior glória não é nunca cair, mas sim levantar sempre que cair.", author: "Confúcio" },
  { text: "Seja a mudança que você deseja ver no mundo.", author: "Mahatma Gandhi" },
  { text: "Tudo parece impossível até ser feito.", author: "Nelson Mandela" },
  { text: "Educação é a arma mais poderosa que você pode usar para mudar o mundo.", author: "Nelson Mandela" },
  { text: "A imaginação é mais importante que o conhecimento.", author: "Albert Einstein" },
  { text: "A medida da inteligência é a capacidade de mudar.", author: "Albert Einstein" },
  { text: "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.", author: "Winston Churchill" },
  { text: "Acredite que você pode, e você já está no meio do caminho.", author: "Theodore Roosevelt" },
  { text: "Faça o que você pode, com o que você tem, onde você está.", author: "Theodore Roosevelt" },
  { text: "O único modo de fazer um excelente trabalho é amar o que você faz.", author: "Steve Jobs" },
  { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
  { text: "Por mais difícil que seja a vida, sempre há algo que você pode fazer e ter sucesso.", author: "Stephen Hawking" },
  { text: "Se cheguei até aqui foi porque me apoiei no ombro dos gigantes.", author: "Isaac Newton" },
  { text: "A simplicidade é o último grau de sofisticação.", author: "Leonardo da Vinci" },
  { text: "O maior perigo não é mirar muito alto e não alcançar, mas mirar muito baixo e alcançar.", author: "Michelangelo" },
  { text: "A vitória pertence ao mais perseverante.", author: "Napoleon Bonaparte" },
  { text: "Quem conhece o inimigo e a si mesmo não precisa temer o resultado de cem batalhas.", author: "Sun Tzu" },
  { text: "Não existe vento favorável para quem não sabe para onde vai.", author: "Sêneca" },
  { text: "Não te envergonhes de errar; envergonha-te de não corrigir os erros.", author: "Sêneca" },
  { text: "Você tem poder sobre sua mente, não sobre eventos externos. Perceba isso e encontrará a força.", author: "Marco Aurélio" },
  { text: "Não exijas que as coisas aconteçam como desejas; deseja as coisas como acontecem e encontrarás paz.", author: "Epicteto" },
  { text: "Faz o que deves e sê o que és.", author: "Epicteto" },
  { text: "Aquele que tem um porquê para viver pode suportar quase qualquer como.", author: "Friedrich Nietzsche" },
  { text: "Acima de tudo, não minta para si mesmo.", author: "Fiódor Dostoiévski" },
  { text: "Todos querem mudar o mundo, mas ninguém quer mudar a si mesmo.", author: "Lev Tolstói" },
  { text: "Nosso destino não está nas estrelas, mas em nós mesmos.", author: "William Shakespeare" },
  { text: "Não tema a grandeza; alguns nascem grandes, alguns alcançam a grandeza.", author: "William Shakespeare" },
  { text: "Eles podem porque acreditam que podem.", author: "Virgílio" },
  { text: "A fortuna favorece os audazes.", author: "Virgílio" },
  { text: "A mente é tudo. No que você pensa, você se torna.", author: "Buda" },
  { text: "A dor é inevitável. O sofrimento é opcional.", author: "Buda" },
  { text: "Gênio é um por cento de inspiração e noventa e nove por cento de transpiração.", author: "Thomas Edison" },
  { text: "Todos os nossos sonhos podem se tornar realidade se tivermos a coragem de persegui-los.", author: "Walt Disney" },
  { text: "Aquele que acredita que pode e aquele que acredita que não pode são ambos certos.", author: "Henry Ford" },
  { text: "A sorte favorece a mente preparada.", author: "Louis Pasteur" },
  { text: "Nada na vida deve ser temido, somente compreendido.", author: "Marie Curie" },
  { text: "Diga-me e eu esqueço. Ensina-me e eu lembro. Envolve-me e eu aprendo.", author: "Benjamin Franklin" },
  { text: "O perfeito é inimigo do bom.", author: "Voltaire" },
  { text: "No meio do inverno, finalmente descobri que havia em mim um verão invencível.", author: "Albert Camus" },
  { text: "A adversidade faz os homens; a prosperidade faz os monstros.", author: "Victor Hugo" },
  { text: "Aquele que abre uma escola fecha uma prisão.", author: "Victor Hugo" },
  { text: "Trate um homem como ele pode ser e ele se tornará o que pode ser.", author: "Goethe" },
  { text: "Seja ousado para começar; a mente tem gênio, poder e magia.", author: "Goethe" },
  { text: "Duas coisas enchem minha mente com admiração: o céu estrelado acima de mim e a lei moral dentro de mim.", author: "Immanuel Kant" },
  { text: "O talento acerta alvos que ninguém mais consegue. O gênio acerta alvos que ninguém mais consegue ver.", author: "Arthur Schopenhauer" },
  { text: "Quem olha para fora, sonha. Quem olha para dentro, desperta.", author: "Carl Jung" },
  { text: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.", author: "Charles Darwin" },
  { text: "O coração tem razões que a própria razão desconhece.", author: "Blaise Pascal" },
  { text: "A dor que você sente hoje é a força que você sentirá amanhã.", author: "Kahlil Gibran" },
  { text: "Quando você quer algo, todo o universo conspira para que você realize seu desejo.", author: "Paulo Coelho" },
  { text: "O sucesso não é um acidente. É trabalho duro, perseverança, aprendizado e amor pelo que você faz.", author: "Pelé" },
  { text: "Impossível é apenas uma palavra encontrada no dicionário dos tolos.", author: "Muhammad Ali" },
  { text: "Posso aceitar o fracasso; todo mundo fracassa em algo. Mas não posso aceitar não tentar.", author: "Michael Jordan" },
  { text: "Uma jornada de mil milhas começa com um único passo.", author: "Lao Tsé" },
  { text: "Aproveite o dia de hoje, confiando o mínimo possível no amanhã.", author: "Horácio" },
  { text: "A gota d'água perfura a pedra não pela força, mas pela constância.", author: "Ovídio" },
  { text: "Ontem era inteligente e queria mudar o mundo. Hoje sou sábio e estou me mudando.", author: "Rumi" },
  { text: "Mudam-se os tempos, mudam-se as vontades.", author: "Luís de Camões" },
  { text: "Tenho em mim todos os sonhos do mundo.", author: "Fernando Pessoa" },
  { text: "Quando sonho sozinho é apenas um sonho. Quando sonhamos juntos é o começo da realidade.", author: "Dom Hélder Câmara" },
  { text: "A vida é tão bela que até viver é pouco.", author: "Machado de Assis" },
  { text: "Não posso parar. Se paro, estou morto.", author: "Ayrton Senna" },
  { text: "Dê-me seis horas para cortar uma árvore e passarei as primeiras quatro afiando o machado.", author: "Abraham Lincoln" },
  { text: "Nada é permanente exceto a mudança.", author: "Heráclito" },
  { text: "A coragem é a virtude que garante todas as outras.", author: "Cícero" },
  { text: "Vim, vi, venci.", author: "Júlio César" },
  { text: "O mais difícil na vida é conhecer a si mesmo.", author: "Tales de Mileto" },
  { text: "Aquele que não está satisfeito com o pouco nunca estará satisfeito com o muito.", author: "Diógenes" },
  { text: "Primeiro princípio: não se engane a si mesmo, pois você é a pessoa mais fácil de enganar.", author: "Richard Feynman" },
  { text: "Você não pode ensinar nada a um homem; pode apenas ajudá-lo a encontrar dentro de si mesmo.", author: "Galileu Galilei" },
  { text: "A grandeza vem de se tornar algo que parecia impossível.", author: "Serena Williams" },
  { text: "O sucesso é o resultado de trabalho duro, aprender com o fracasso, lealdade e persistência.", author: "Kobe Bryant" },
  { text: "Alguém está sentado na sombra hoje porque alguém plantou uma árvore há muito tempo.", author: "Warren Buffett" },
  { text: "Quando algo é importante o suficiente, você o faz mesmo que as probabilidades não estejam ao seu favor.", author: "Elon Musk" },
  { text: "A vida é o que acontece quando você está fazendo outros planos.", author: "John Lennon" },
  { text: "O sucesso é um péssimo professor. Ele seduz pessoas inteligentes a pensar que não podem perder.", author: "Bill Gates" },
  { text: "A fé em si mesmo é o primeiro segredo do sucesso.", author: "Ralph Waldo Emerson" },
  { text: "Você nunca é velho demais para definir um novo objetivo ou sonhar um novo sonho.", author: "C.S. Lewis" },
  { text: "O único modo de descobrir os limites do possível é ir além deles.", author: "Arthur C. Clarke" },
  { text: "Visite o país que você ainda não visitou: você mesmo.", author: "José Saramago" },
  { text: "A vida começa onde o medo termina.", author: "Osho" },
  { text: "Não é a montanha que conquistamos, mas a nós mesmos.", author: "Edmund Hillary" },
  { text: "O amanhã pertence àqueles que se preparam hoje.", author: "Malcolm X" },
  { text: "O segredo para ir adiante é começar.", author: "Mark Twain" },
  { text: "A perseverança não é uma corrida longa; é muitas corridas curtas uma após a outra.", author: "Walter Elliot" },
  { text: "A vida é curta demais para ser pequena.", author: "Benjamin Disraeli" },
  { text: "O campeão não é aquele que nunca cai, mas aquele que sempre se levanta.", author: "Vince Lombardi" },
  { text: "Não espere. A hora nunca será perfeita.", author: "Napoleon Hill" },
  { text: "O mundo é um livro e aqueles que não viajam leem apenas uma página.", author: "Santo Agostinho" },
  { text: "A diferença entre o possível e o impossível está na determinação.", author: "Tommy Lasorda" },
  { text: "Se a oportunidade não bater à sua porta, construa uma porta.", author: "Milton Berle" },
  { text: "O talento sem trabalho é apenas talento.", author: "Ronaldo Nazário" },
  { text: "Criar é resistir.", author: "Agostinho Neto" },
  { text: "Cada momento é uma chance de recomeçar.", author: "T.S. Eliot" },
];
